// client/src/components/Header/Menu/index.tsx
import React from "react";
import { Link, useNavigate } from "react-router-dom";
import styled from "styled-components";
import { CSSTransition } from 'react-transition-group';

import Header from "./Header";
import Item from "./Item";
import SubItem from "./SubItem";
import Disclaimer from "./Disclaimer";

import api from "$services/api";


const Container = styled.div`
  .menu-enter {
    transform: translateX(300px);
  }
  .menu-enter-active {
    transform: translateX(0);
    transition: transform 300ms;
  }
  .menu-exit {
    transform: translateX(0);
  }
  .menu-exit-active {
    transform: translateX(300px);
    transition: transform 300ms;
  }

  .background-enter {
    background-color: #fff0;
  }
  .background-enter-active {
    background-color: #0007;
    transition: background-color 300ms;
  }
  .background-enter-done {
    background-color: #0007;
  }
  .background-exit {
    background-color: #0007;
  }
  .background-exit-active {
    background-color: #fff0;
    transition: background-color 300ms;
  }
`;

const Background = styled.div`
  position: fixed;
  top: 50px;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: 1;
`

const MenuContainer = styled.div`
  width: 300px;
  position: fixed;
  top: 50px;
  right: 0;
  z-index: 1;
`

type Props = {
  active: boolean,
  onHide: () => void
}

export default ({ active, onHide }: Props) => {
  const navigate = useNavigate();

  const signOut = async () => {
    await api.signOut();
    navigate("/login")
  }

  return (
    <Container>
      <CSSTransition
        in={active}
        timeout={300}
        classNames="background"
        unmountOnExit
      >
        <Background onClick={onHide} />
      </CSSTransition>
      <CSSTransition
        in={active}
        timeout={300}
        classNames="menu"
        unmountOnExit
      >
        <MenuContainer>
          <Header />
          <Item>Home</Item>
          <Item>Lessons</Item>
          <Item>Training</Item>
          <Disclaimer />
          <Item>Languages</Item>
          <SubItem>English</SubItem>
          <SubItem>Spanish</SubItem>
          <SubItem>German</SubItem>
          <Disclaimer />
          <Item onClick={signOut}>Sign out</Item>
        </MenuContainer>
      </CSSTransition>
    </Container>
  )
  }

// client/src/UI/Menu/Menu.svelte
<script>
  import { fade, fly } from "svelte/transition";
  import { push, location } from "svelte-spa-router";

  import MenuItem from "./MenuItem.svelte";
  import SubMenuItem from "./SubMenuItem.svelte";
  import Header from "./Header.svelte";
  import Disclaimer from "./Disclaimer.svelte";

  import Api from "../../services/api";
  import Navigation from "../../services/navigation";

  import userStore from "../../stores/user";

  export let isOpen = false;

  let loading = false;

  let currentLink = $location;
  $: if (currentLink !== $location) {
    isOpen = false;
    currentLink = $location;
  }

  const goTo = (path) => {
    isOpen = false;
    push(path);
  };

  const signOut = async () => {
    loading = true;
    try {
      await Api.signOut();
      userStore.signOut();
      Navigation.goToLogin();
    } catch (error) {
    } finally {
      loading = false;
    }
  };
</script>

<div
  transition:fade={{ duration: 300 }}
  class="background"
  on:click={() => (isOpen = false)}
/>

<div transition:fly={{ duration: 200, x: 300 }} class="menu-container">
  <Header />
  <MenuItem on:click={() => goTo("/")}>Home</MenuItem>
  <MenuItem on:click={() => goTo("/lessons")}>Lessons</MenuItem>
  <MenuItem on:click={() => goTo("/training")}>Training</MenuItem>
  <Disclaimer />
  <MenuItem>Languages</MenuItem>
  <SubMenuItem>English</SubMenuItem>
  <SubMenuItem>Spanish</SubMenuItem>
  <SubMenuItem>German</SubMenuItem>
  <Disclaimer />
  <MenuItem on:click={signOut}>Sign out</MenuItem>
</div>

<style>
  .menu-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    position: absolute;
    z-index: 1;
    top: 50px;
    bottom: 0;
    right: 0;
    background-color: white;
    box-shadow: 0 0 8px rgb(0 0 0 / 25%);
  }

  .background {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    background-color: #0007;
    z-index: 1;
  }
</style>
