// client/src/UI/Menu/Header.svelte
<script>
  import userStore from "../../stores/user";
</script>

<div class="menu-header">
  <div>
    <i class="eva eva-person-outline" />
  </div>
  <div>
    {$userStore.email}
  </div>
</div>

<style>
  .menu-header {
    height: 60px;
    width: 100%;
    background-color: #eee;
    border-bottom: 1px solid #ddd;
    display: flex;
    align-items: center;
    padding-left: 15px;
    cursor: pointer;
  }

  i {
    font-size: 30px;
    margin-right: 10px;
  }
</style>

// client/src/components/Header/Menu/Header.tsx
import styled from "styled-components";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faHouse, faUser } from '@fortawesome/free-solid-svg-icons'

import { useAppSelector, useAppDispatch } from '../../../hooks';

const Container = styled.div`
  height: 60px;
  width: 100%;
  background-color: #eee;
  border-bottom: 1px solid #ddd;
  display: flex;
  align-items: center;
  padding-left: 15px;
  cursor: pointer;
`;

export default () => {
  const email = useAppSelector(state => {
    return state.user.email
  })
  return (
    <Container>
      <div>
        <FontAwesomeIcon icon={faUser} />
      </div>
      <div>
        {email}
      </div>
    </Container>
  )
}
